services:
  - type: web
    name: backend-first-principles-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FRONTEND_ORIGIN
        value: https://backend200.vercel.app
      - key: DATABASE_URL
        sync: false
